#!/usr/bin/env python
# -*- coding: utf-8 -*- 

'''
  ------------------------------------------
  
  WireChem - The new chemistry game
  
  Programme de génération de données au format "Shelves"

  (C) Copyright 2013-2014 Nicolas Hordé
  Licence GPL V3.0
  
  ------------------------------------------
'''

import shelve

def write(afile,var):
	d=shelve.open(afile,writeback=True)
	for k in var:
		d[k]=globals()[k]
	d.sync()
	d.close()


global worlds

worlds=[[{'nom': 'Introduction',
  'description': "Prise en main de l'interface de WireChem{#169} et amener l'électron neutre sur le senseur.",
  'element': 'e0',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'cout': 0,
  'tech': -1,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 38,
  '_yy': 450,
  'link': [(0, 1), (0, 8)],
  'video': True,
  'world_art': [[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 196637, 0, 0], 
				[0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0], 
				[0, 0, 16, 0, 0], 
				[0, 0, 4096, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 0, 0, 0]], 
				
 'tuto':'''
del
select 0,5,2
select 0,6,3
select 0,7,1
msg Bienvenu(e) dans le tutoriel du premier niveau de WireChem; nous allons vous expliquer pas à pas le fonctionnement du jeu.                                   <Cliquez ou appuyez sur une touche pour continuer>
wait
msg L'interface du jeu est séparée en 3 grandes zones distinctes; chaque zone verra ses particularités évoluer au fur et à mesure de l'avancée du jeu.
wait 5
rect 2,766,1022,720
set 1,5
msg La barre du haut est une barre d'informations sur l'état du jeu. Actuellement elle n'est remplie que de l'objectif du niveau qui clignote en rouge.
wait 8
unset 1,5
rect 2,720,1022,50
msg La partie centrale est la zone de jeu à proprement parler où vous allez créer votre modèle puis vérifier par simulation qu'il remplisse les objectifs du niveau en cours.
wait 8
rect 2,2,1022,50
msg La barre du bas comporte plusieurs icônes que l'on peut sélectionner afin de réaliser différentes actions. Les 3 rectangles colorés représentent les actions déclenchables par les 3 boutons de la souris.
wait 8
arrow 635,145,300,50
set 0,7
msg En cliquant avec le bouton gauche n'importe où sur l'écran; vous allez déclencher l'action dézoomer représentée en rouge.             <Testez cette action en appuyant sur le bouton gauche.>
wait click,1
unset 0,7
arrow 635,145,210,50
set 0,5
msg Bravo !! L'action réalisée par le bouton droit est affichée en bleu et celle par le bouton de la molette en vert. Celle-ci nécessite un glisser déposer ce qui fait bouger le plateau de jeu.      <Essayez le bouton de la molette!>
wait drag,2
unset 0,5
arrow 635,145,390,50
set 0,9
msg Ce bouton vous fera quitter le niveau Intruction pour revenir au monde de l'Hydrogène qui la contient.
wait 5
unset 0,9
arrow 635,145,480,50
set 0,13
msg Ce bouton d'options vous permettra de régler les options vidéo du jeu ainsi que le son.
wait 4
unset 0,13
arrow 635,145,530,50
set 0,14
msg Par ici la sortie !!! non; n'y touchez surtout pas tout de suite; le jeu ne fait que commencer ...
wait 4
unset 0,14
del
center
msg Passons maintenant à l'objectif du niveau : obtenir un électron neutre sur le senseur.                                   <Cliquez ou appuyez sur une touche pour continuer>
wait
arrow 144,260,145,370
msg Un électron neutre est représenté en gris et possède une tête plus foncée précédant une queue plus claire. 
wait 3
arrow 54,260,55,370
wait 3
msg Voici le senseur... Cet élément accepte les électrons comme l'indique le e. Il est neutre d'où sa couleur grise et valide l'objectif à atteindre pour ce niveau.  
arrow 974,260,975,340
wait 5
msg Les électrons ne peuvent se déplacer que sur des pistes de cuivre qui sont de couleur orange.
arrow 499,260,500,370 
wait 5
del
msg Voici le déplacement pas à pas de l'électron sur la piste de cuivre qui le sépare du senseur.
wait 3
next
wait 1
next
wait 1
next
wait 2
arrow 635,145,30,50
set 0,1
msg "Le bouton play permet de passer en mode simulation. Alors la limite de la zone de jeu devient rouge et l'interface s'anime. Passons à la pratique !!                               <Cliquez sur le bouton play>
'''},

 {'nom': 'Trajectoires',
  'description': 'Comprendre les trajectoires empruntées par les électrons afin de mieux appréhender la conception de systèmes.',
  'element': 'e0',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'cout': 0,
  'tech': -1,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 38,
  '_yy': 200,
  'link': [(0, 2)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 196637, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 1, 0, 1, 1, 16, 0, 0], 
				[0, 1, 0, 1, 0, 0, 4096, 0, 0], 
				[0, 1, 0, 1, 0, 1, 0, 1, 0], 
				[0, 1, 0, 1, 0, 1, 0, 1, 0], 
				[0, 1, 0, 1, 0, 0, 1, 0, 0], 
				[0, 0, 1, 1, 0, 0, 1, 0, 0], 
				[0, 1, 0, 1, 0, 1, 1, 1, 0], 
				[0, 1, 0, 1, 0, 1, 0, 1, 0], 
				[0, 1, 0, 1, 0, 1, 1, 1, 0], 
				[0, 0, 1, 1, 0, 0, 1, 0, 0], 
				[0, 1, 0, 1, 0, 0, 1, 0, 0], 
				[0, 1, 0, 1, 0, 1, 1, 1, 0], 
				[0, 1, 1, 1, 0, 1, 1, 1, 0], 
				[0, 1, 1, 1, 0, 0, 1, 0, 0], 
				[0, 1, 1, 1, 1, 1, 1, 0, 0], 
				[0, 0, 0, 1, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],

 'tuto':'''
del
msg Nous allons voir comment se déplace un électron; ici neutre; mais les règles de déplacements seront valables pour tous les types d'électrons.                 <Cliquez ou appuyez sur une touche pour continuer>
wait 
msg Les positionnements de la tête et de la queue de l'électron indiquent son sens; ici de la gauche vers la droite. L'électron se trouve face à deux pistes allant en diagonale par rapport à son emplacement initial.              Que fera-t-il?
arrow 30,510,110,510
wait 10
msg Suivez maintenant pas à pas le trajet de l'électron...
wait 3
del
next
msg Dans ce cas; l'électron a autant de chances d'emprunter l'une que l'autre des deux pistes.                             Le choix se fait de façon aléatoire.
wait 10
next
wait 1
next
wait 1
next
msg L'électron se trouve à nouveau face à une intersection mais cette fois les pistes sont perpendiculaires par rapport à sa position actuelle. 
wait 10
next
wait 1
next
msg Comme pour les diagonales; il a autant de chances d'aller vers la piste du haut que vers celle du bas.                        A noter qu'il se déplace préférentiellement en diagonale s'il le peut afin de toujours prendre le chemin le plus court.
wait 10
next
wait 1
next
wait 1
next
msg Dans ce cas de figure; si la piste de cuivre sur laquelle il se trouve le permet; l'électron ira toujours tout droit en raison de son inertie.
wait 10
next
wait 1
next
wait 1
next
wait 1
next
wait 1
next
wait 1
next
msg Pour que l'électron atteigne le senseur et que l'objectif du niveau soit rempli; à vous de continuer la simulation en cliquant sur le bouton play !!
wait menu,0,1
msg Le mode play est parti !!!
'''},
 
 {'nom': 'Pistes',
  'description': "Utiliser des pistes afin de réaliser un circuit qui permet l'arrivée d'un électron neutre sur le senseur.",
  'element': 'e0',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'cout': 15,
  'tech': 0,
  'cycle': 0,
  'maxcycle': 99999, 
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 180,
  '_yy': 300,
  'link': [(0, 3)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 196637, 0, 0], 
				[0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0], 
				[0, 0, 16, 0, 0], 
				[0, 0, 4096, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 0, 0, 0]], 
				
 'tuto':'''
del
msg De nouveaux icônes sont apparus ! Voyons ensemble les possibilités de chacun ...
wait 5
arrow 804,670,805,720
msg Voici le détail des conditions de victoire pour atteindre l'objectif de chaque niveau.                                   Il faut ici un électron neutre.
wait 7
arrow 34,670,35,720
set 1,1
msg Cet icône correspond au nombre de cycles. Un cycle représente pour chaque élément mobile du jeu; comme les électrons; 1 déplacement.            Le nombre de cycles ne varie qu'en mode simulation.
wait 12
unset 1,1
arrow 635,145,75,50
set 0,2
msg Ce bouton représente la vitesse en mode simulation; plus vous cliquerez dessus plus la vitesse des éléments mobiles du jeu va augmenter. La jauge sur le côté augmentera jusqu'à revenir à la vitesse la plus lente.
wait 12
unset 0,2
del
set 0,22
msg Cet icône ne trompe pas; vous avez ici votre réserve d'argent disponible associée à ce niveau. Attention à ne pas tout dépenser; sinon vous ne pourrez plus ajouter d'élément dans la zone de jeu.
wait 12
unset 0,22
msg A partir de ce niveau; vous allez prendre en main la création de votre modèle de simulation !!
wait 7
arrow 635,145,565,50
set 0,15
msg Vous aurez besoin de pistes de cuivre. Cliquez pour cela sur l'icône orange. <Sélectionnez l'outil cuivre> 
wait menu,0,15
unset 0,15
del
msg Créer ensuite votre piste soit en cliquant une fois pour déposer une case de piste; soit en cliquant en continu pour tracer un trajet. 
wait create
msg Bravo !! Si vous souhaitez rectifier votre tracé; cliquez sur la case noire.  <Sélectionnez l'outil effacer> 
set 0,17
wait menu,0,17
unset 0,17 
msg Effacer vos erreurs...Vous ne pouvez retirer que les éléments que vous avez ajoutés à la zone de jeu. 
wait erase
msg Vous progressez dans l'apprentissage des bases de Wirechem; vous êtes maintenant prêt à finir le niveau; alors à vous de jouer !!
'''},
 
 {'nom': 'Positiveur',
  'description': "Comprendre le fonctionnement de l'élément positiveur et générer 8 électrons positifs sur le senseur.",
  'element': 'e+',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0],
  'cout': 16,
  'tech': 0,
  'cycle': 0, 
  'maxcycle': 99999,  
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,   
  'temp': 0,     
  'maxtemp': 99999,
  '_xx': 330,
  '_yy': 350,
  'link': [(0, 4)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0], 
				[0, 0, 196642, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 196641, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 196638, 0, 0], 
				[0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 0, 0, 0]],
				
 'tuto':'''
del	 
arrow 54,255,55,340
msg Ce niveau vous fait découvrir d'autres éléments de jeu : tout d'abord un canon à électrons; représenté ici par un carré violet. Il délivrera un électron tous les 40 cycles.
wait 8
arrow 514,255,515,340
msg Ce + rouge est un positiveur. Lorsqu'un électron passera dessus; il deviendra positif et prendra alors la couleur rouge.
wait 8
arrow 969,255,970,340 
msg Vous connaissez déjà le senseur gris acceptant les électrons neutres; voici le senseur rouge pour les électrons positifs.
wait 8
rect 830,765,870,720
msg A vous maintenant d'atteindre les conditions de victoire !!
'''},	 
	   
 {'nom': 'Super-électrons',
  'description': 'Générer 2 super-électrons negatifs par colision et les amener sur le senseur',
  'element': 'E-',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'cout': 81,
  'tech': 1,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,  
  'rayon': 0,
  'maxrayon': 99999,  
  'temp': 0,   
  'maxtemp': 99999,
  '_xx': 490,
  '_yy': 380,
  'link': [(0, 5)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0], 
				[0, 196624, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 196641, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 196639, 0, 0], 
				[0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0], 
				[0, 1, 1, 1, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 1, 0, 0], 
				[0, 0, 0, 0, 0]],
				
 'tuto':'''
del	 
arrow 635,145,165,50
set 0,4
msg De nouveaux icônes font leur apparition : à partir de ce niveau; vous pourrez enregistrer votre modèle de simulation en cliquant sur la disquette.
wait 10
unset 0,4
arrow 635,145,120,50
set 0,3
msg Les modèles enregistrés seront stockés dans le dossier de sauvegarde.                            <Cliquez dessus pour dérouler le menu de sauvegarde> 
wait menu,0,3
unset 0,3
rect 2,40,1022,90
wait 2
arrow 635,145,30,90
msg Le signe dièse représente la version originale du niveau; vos sauvegardes seront ensuite classées à côté en suivant l'alphabet grec.                         <Essayer pour tester en cliquant sur la disquette>
wait menu,0,4
del
msg La lettre alpha constituera toujours la sauvegarde la plus récente.                <Cliquez à nouveau sur le dossier de sauvegarde pour refermer ce menu>
wait menu,0,3
set 0,23
msg L'icône représentant un microscope vous indiquera le degré technologique du niveau. Plus vous progresserez dans Wirechem; plus ce degré augmentera ce qui vous octroiera de nouveaux éléments de jeu.
wait 12
unset 0,23
set 0,18
msg Ici vous trouverez le menu contenant les transmuteurs qui sont les éléments de jeu auxquels vous avez accès en étant au degré technologique 1 !!      <Cliquez pour les découvrir>
wait menu,0,18
unset 0,18
rect 2,40,1022,90
wait 2
msg Vous connaissez déjà le canon à électrons; l'inverseur (+/-) vous permettra de faire varier la charge d'un électron de positive (rouge) en négative (bleu) et vice et versailles.
arrow 580,150,579,90
wait 4
arrow 125,150,124,90
wait 8
del
msg Vous avez tous les éléments en mains pour atteindre l'objectif de ce niveau : obtenir 2 super-électrons négatifs. Qu'est-ce que cette bête là ???
wait 8
msg Un super-électron est créé lorsque deux électrons positifs ou négatifs vont entrer en collision. Sa queue sera alors rallongée d'un élément et sa tête prendra une couleur plus vive !!
wait 12
msg Assez d'explications; à vous de travailler un peu !!
'''},			
 
 {'nom': 'Activation',
  'description': "L'objectif est de générer 6 électrons neutres et de découvrir les liaisons de fibres par lesquelles transitent les photons. Certains modifieurs nécessitent désormais l'activation par des photons.",
  'element': 'e0',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'cout': 136,
  'tech': 1,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999, 
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,  
  'maxtemp': 99999,
  '_xx': 490,
  '_yy': 200,
  'link': [(0, 6)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0], 
				[0, 0, 196624, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 196627, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0], 
				[0, 0, 0, 196640, 0], 
				[0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0], 
				[0, 2, 1, 0, 0], 
				[0, 0, 2, 0, 0], 
				[0, 0, 2, 1, 0], 
				[0, 2, 0, 0, 0], 
				[0, 2, 0, 0, 0], 
				[0, 2, 0, 0, 0], 
				[0, 2, 0, 0, 0], 
				[0, 2, 2, 1, 0], 
				[0, 2, 0, 4096, 0]], 
				
 'tuto':'''
del	 
msg Le jeu étant trop simple à notre goût; les règles vont donc se corser un peu avec le principe d'activation. Voyons ensemble en quoi cela consiste ...
wait 8
arrow 64,270,65,370
msg Chaque transmuteur possèdant des triangles blancs dans ses coins; comme ici le canon à électrons; sera un élément dit activable par un nouvel élément mobile : le photon !!
wait 10
arrow 250,250,251,350
msg Comme l'électron; le photon possède deux unités : une tête de couleur vert foncé et une queue plus claire. Les photons se déplaceront uniquement sur des fibres; pistes de couleur verte que vous voyez sur la zone jeu. 
wait 12
arrow 320,370,321,470
msg Le photoniseur vous permettra de créer des photons. Lorsqu'un électron passera sur ce dernier; il se transformera en photon puis ira sur la case de fibre placée au contact du photoniseur.
wait 10
del
msg A noter : un transmuteur inactif est blanc. Suite au passage d'un photon à sa proximité; il sera activé et se colorera mais seulement pendant 10 cycles. Il reprendra sa forme inactive jusqu'au prochain passage de photon.  
wait 12
msg Il faudra donc gérer l'activation de certains transmuteurs pour dorénavant remplir les conditions de victoire; à vous de tester maintenant !!
wait 8
'''},	
 
 {'nom': 'Fibres',
  'description': 'A vous de dessiner votre infrastructure à base de fibres et de pistes mais aussi de modifieur activable afin de faire parvenir des éléctrons positifs et neutres sur les senseurs.',
  'element': 'eX',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0],
  'cout': 230,
  'tech': 2,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,  
  'maxnrj': 99999, 
  'rayon': 0, 
  'maxrayon': 99999, 
  'temp': 0,  
  'maxtemp': 99999,
  '_xx': 640,
  '_yy': 200,
  'link': [(0, 7)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 196640, 0, 0, 0, 0], 
				[0, 0, 196638, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 1, 2, 1, 2, 1, 0, 0], 
				[0, 0, 1, 2, 1, 2, 1, 0, 0], 
				[0, 0, 1, 2, 2, 2, 1, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]], 
				
 'tuto':'''
del	
set 0,16 
msg Vous venez de faire connaissance avec les photons; la fibre et le photoniseur. Vous pouvez maintenant avoir accès à la fibre sur le même principe que les pistes de cuivre; et au photoniseur dans le menu des transmuteurs.
wait 10
unset 0,16
msg 


'''},	
 
 {'nom': 'Protons',
  'description': "Générer deux protons sur le senseur en utilisant un réacteur et un super-positron. Le réacteur est un élément qui nécessite l'activation.",
  'element': 'p',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
  'cout': 370,
  'tech': 2,
  'cycle': 0,
  'maxcycle': 99999, 
  'nrj': 0, 
  'maxnrj': 99999,
  'rayon': 0,  
  'maxrayon': 99999, 
  'temp': 0, 
  'maxtemp': 99999,
  '_xx': 800,
  '_yy': 290,
  'link': [(0, 8)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 196624, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 196627, 0, 0, 0, 0], 
				[0, 0, 196635, 0, 0, 0, 196629, 196609, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 1, 1, 1, 0], 
				[0, 0, 0, 0, 1, 2, 1, 1, 0], 
				[0, 0, 0, 1, 2, 1, 1, 1, 0], 
				[0, 0, 0, 2, 1, 2, 1, 0, 0], 
				[0, 0, 0, 2, 1, 1, 2, 1, 0], 
				[0, 0, 2, 2, 1, 1, 2, 1, 0], 
				[0, 2, 0, 0, 0, 0, 1, 1, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]]}, 
 
 {'nom': 'Hydrogène',
  'description': "Générer le premier atome complet : l'hydrogène avec un proton et un électron négatif sur la couche K.",
  'element': 'H',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
  'cout': 750,
  'tech': 3,
  'cycle': 0,  
  'maxcycle': 99999,     
  'nrj': 0,   
  'maxnrj': 99999, 
  'rayon': 0,  
  'maxrayon': 99999,   
  'temp': 0,     
  'maxtemp': 99999,
  '_xx': 900,
  '_yy': 450,
  'link': [(1, 0), (1, 2)],
  'video': False,
  'special': True,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 196619, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 1, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]]}], 
 
[{'nom': 'Deutérium',
  'description': "Générer le Deutérium, un isostope de l'hydrogène, celui-ci comporte un neutron en plus du proton et de l'électron négatif sur la couche K.",
  'element': 'D',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
  'cout': 1100,
  'tech': 4,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 30,
  '_yy': 450,
  'link': [(1, 1)],
  'video': False, 
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 196619, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 1, 1, 0, 0, 0, 0, 0], 
				[0, 1, 0, 1, 0, 0, 0, 0, 0], 
				[0, 1, 1, 1, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]]}, 
 
 {'nom': 'Tritium',
  'description': "Générer le second isostope de l'hydrogène : cet atome plus lourd que le Deutérium comporte alors deux neutrons, un proton ainsi qu'un électron négatif sur la couche K.",
  'element': 'T',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1],
  'cout': 1000,
  'tech': 4,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 420,
  '_yy': 450,
  'link': [],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 196619, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 1, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]]},  
 
{'nom': 'Hélium-4',
  'description': "L'isotope le plus courant de l'Hélium dans l'atmosphère terrestre est l'Hélium-4. Générer le en associant deux protons, deux neutrons et deux électrons négatifs sur la couche K.",
  'element': 'He',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2],
  'cout': 1200,
  'tech': 4,
  'cycle': 800,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 30,
  '_yy': 250,
  'link': [(1,3),(1,5)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 196620, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]}, 
 
 {'nom': 'Hélium-3',
  'description': "Générer le seul autre isotope stable de l'hélium, ce dernier n'étant présent qu'à l'état de traces sur Terre. Cet isotope comporte deux protons,un neutron et deux électrons négatifs sur la couche K.",
  'element': 'He',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2],
  'cout': 1300,
  'tech': 5,
  'cycle': 0,
  'maxcycle': 700,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 180,
  '_yy': 190,
  'link': [(1, 4)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 196620, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]}, 
 
 {'nom': 'Hélium-8',
  'description': "l'Hélium-8 est le plus étudié des isotopes lourds de l'Hélium avec l'Hélium-6. Cet isostope comporte deux protons, six neutrons et deux électrons négatifs sur la couche K.",
  'element': 'He',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 6, 2],
  'cout': 1500,
  'tech': 5,
  'cycle': 0,
  'maxcycle': 1800,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 420,
  '_yy': 190,
  'link': [],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 196622, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 196620, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]}, 
 
 {'nom': 'Lithium',
  'description': "Générer un isostope de l'hydrogène qui comporte un proton et un neutron ainsi qu'un électron négatif sur la couche K.",
  'element': 'Li',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
  'cout': 1200,
  'tech': 4,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 300,
  '_yy': 320,
  'link': [(1, 6)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 196619, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 1, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]]}, 
 
 {'nom': 'Carbone',
  'description': "Générer un isostope de l'hydrogène qui comporte un proton et un neutron ainsi qu'un électron négatif sur la couche K.",
  'element': 'C',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
  'cout': 1200,
  'tech': 4,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 550,
  '_yy': 320,
  'link': [(1, 7)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 196619, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 1, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]]}, 
 
 {'nom': 'Oxygène',
  'description': "Générer un isostope de l'hydrogène qui comporte un proton et un neutron ainsi qu'un électron négatif sur la couche K.",
  'element': 'O',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
  'cout': 1200,
  'tech': 4,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 720,
  '_yy': 380,
  'link': [(1, 8)],
  'video': False,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 196619, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 1, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]]}, 
	
 {'nom': 'Néon',
  'description': "Générer un isostope de l'hydrogène qui comporte un proton et un neutron ainsi qu'un électron négatif sur la couche K.",
  'element': 'Ne',
  'current': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  'victory': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1],
  'cout': 1200,
  'tech': 4,
  'cycle': 0,
  'maxcycle': 99999,
  'nrj': 0,
  'maxnrj': 99999,
  'rayon': 0,
  'maxrayon': 99999,
  'temp': 0,
  'maxtemp': 99999,
  '_xx': 900,
  '_yy': 450,
  'link': [],
  'video': False,
  'special': True,
  'world_art': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 196619, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]],
  'world_new': [[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 0, 0, 0, 0, 0, 0, 0], 
				[0, 1, 1, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0], 
				[0, 0, 0, 0, 0, 0, 0, 0, 0]]}]]
art={
196608: {'nrj': 0, 'cout': 0, 'temp': 0, 'nom': 'null', 'color': [0, 0, 0], 'text': '', 'value': 196608, 'cat': 0, 'tech': 0, 'activable': False},
196609: {'nrj': 0, 'cout': 60, 'temp': 0.05, 'nom': 'positiver', 'color': [255, 0, 0], 'text': '+', 'value': 196609, 'cat': 1, 'tech': 2, 'activable': True},
196610: {'nrj': 0, 'cout': 60, 'temp': 0.05, 'nom': 'negativer', 'color': [0, 0, 255], 'text': '-', 'value': 196610, 'cat': 1, 'tech': 4, 'activable': True},
196611: {'nrj': 0, 'cout': 20, 'temp': 0.05, 'nom': 'inverter', 'color': [125, 13, 114], 'text': '±', 'value': 196611, 'cat': 1, 'tech': 1, 'activable': False},
196612: {'nrj': 0, 'cout': 20, 'temp': 0.05, 'nom': 'neutraliser', 'color': [90, 90, 90], 'text': '~', 'value': 196612, 'cat': 1, 'tech': 4, 'activable': False},
196613: {'nrj': 0, 'cout': 25, 'temp': 0.05, 'nom': 'dir1', 'color': [125, 13, 114], 'text': '◄', 'value': 196613, 'cat': 2, 'tech': 5, 'activable': False},
196614: {'nrj': 0, 'cout': 25, 'temp': 0.05, 'nom': 'dir2', 'color': [125, 13, 114], 'text': '►', 'value': 196614, 'cat': 2, 'tech': 5, 'activable': False},
196615: {'nrj': 0, 'cout': 150, 'temp': 0.05, 'nom': 'trierb', 'color': [0, 0, 255], 'text': '▪', 'value': 196615, 'cat': 3, 'tech': 6, 'activable': False},
196616: {'nrj': 0, 'cout': 150, 'temp': 0.05, 'nom': 'trierr', 'color': [255, 0, 0], 'text': '▪', 'value': 196616, 'cat': 3, 'tech': 6, 'activable': False},
196617: {'nrj': 0, 'cout': 200, 'temp': 0.05, 'nom': 'trierp', 'color': [44, 120, 44], 'text': '▪', 'value': 196617, 'cat': 3, 'tech': 8, 'activable': True},
196618: {'nrj': 0, 'cout': 150, 'temp': 0.05, 'nom': 'trierg', 'color': [125, 13, 114], 'text': '↕', 'value': 196618, 'cat': 3, 'tech': 5, 'activable': False},
196619: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern1-1', 'color': [125, 13, 114], 'text': '1', 'value': 196619, 'cat': 3, 'tech': 8, 'activable': False},
196620: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern2-2', 'color': [125, 13, 114], 'text': '2', 'value': 196620, 'cat': 3, 'tech': 8, 'activable': False},
196621: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern4-4', 'color': [125, 13, 114], 'text': '4', 'value': 196621, 'cat': 3, 'tech': 8, 'activable': False},
196622: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern4-4a', 'color': [125, 13, 114], 'text': '4', 'value': 196622, 'cat': 3, 'tech': 9, 'activable': True},
196623: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern8-8a', 'color': [125, 13, 114], 'text': '8', 'value': 196623, 'cat': 3, 'tech': 9, 'activable': True},
196624: {'nrj': 1, 'cout': 50, 'temp': 0, 'nom': 'canonh', 'color': [90, 90, 90], 'text': '■', 'value': 196624, 'cat': 4, 'tech': 1, 'activable': True},
196625: {'nrj': 0, 'cout': 20, 'temp': 0, 'nom': 'canont', 'color': [90, 90, 90], 'text': '□', 'value': 196625, 'cat': 4, 'tech': 5, 'activable': True},
196626: {'nrj': 0, 'cout': 40, 'temp': 0, 'nom': 'destroyer', 'color': [125, 13, 114], 'text': 'X', 'value': 196626, 'cat': 4, 'tech': 7, 'activable': False},
196627: {'nrj': 0, 'cout': 30, 'temp': 0.5, 'nom': 'photonizer', 'color': [44, 120, 44], 'text': '≠', 'value': 196627, 'cat': 4, 'tech': 2, 'activable': False},
196628: {'nrj': 0, 'cout': 150, 'temp': 1.0, 'nom': 'photonizer2', 'color': [44, 120, 44], 'text': '=', 'value': 196628, 'cat': 4, 'tech': 8, 'activable': False},
196629: {'nrj': 0, 'cout': 100, 'temp': 2, 'nom': 'reactor', 'color': [125, 13, 114], 'text': 'Φ', 'value': 196629, 'cat': 4, 'tech': 3, 'activable': True},
196630: {'nrj': 0, 'cout': 80, 'temp': 0, 'nom': 'senserK', 'color': [50, 50, 150], 'text': 'K', 'value': 196630, 'cat': 5, 'tech': 3, 'activable': True},
196631: {'nrj': 0, 'cout': 80, 'temp': 0, 'nom': 'senserL', 'color': [50, 50, 150], 'text': 'L', 'value': 196631, 'cat': 5, 'tech': 6, 'activable': True},
196632: {'nrj': 0, 'cout': 80, 'temp': 0, 'nom': 'senserM', 'color': [50, 50, 150], 'text': 'M', 'value': 196632, 'cat': 5, 'tech': 7, 'activable': True},
196633: {'nrj': 0, 'cout': 80, 'temp': 0, 'nom': 'senserN', 'color': [50, 50, 150], 'text': 'N', 'value': 196633, 'cat': 5, 'tech': 8, 'activable': True},
196634: {'nrj': 0, 'cout': 80, 'temp': 0, 'nom': 'sensern', 'color': [75, 119, 157], 'text': 'n', 'value': 196634, 'cat': 5, 'tech': 4, 'activable': True},
196635: {'nrj': 0, 'cout': 80, 'temp': 0, 'nom': 'senserp', 'color': [122, 49, 25], 'text': 'p', 'value': 196635, 'cat': 5, 'tech': 3, 'activable': True},
196636: {'nrj': 0, 'cout': 300, 'temp': 0, 'nom': 'calor', 'color': [240, 30, 30], 'text': 'Ж', 'value': 196636, 'cat': 6, 'tech': 9, 'activable': False},
196637: {'nrj': 0, 'cout': 0, 'temp': 0, 'nom': 'sensere', 'color': [60, 60, 60], 'text': 'e', 'value': 196637, 'cat': 7, 'tech': 0, 'activable': False},
196638: {'nrj': 0, 'cout': 0, 'temp': 0, 'nom': 'senserf', 'color': [200, 50, 50], 'text': 'e', 'value': 196638, 'cat': 7, 'tech': 0, 'activable': False},
196639: {'nrj': 0, 'cout': 0, 'temp': 0, 'nom': 'senserg', 'color': [0, 0, 255], 'text': 'e', 'value': 196639, 'cat': 7, 'tech': 0, 'activable': False},
196640: {'nrj': 0, 'cout': 0, 'temp': 0, 'nom': 'senserh', 'color': [60, 60, 60], 'text': 'e', 'value': 196640, 'cat': 7, 'tech': 0, 'activable': True},
196641: {'nrj': 0, 'cout': 0, 'temp': 0.05, 'nom': 'positiver2', 'color': [255, 0, 0], 'text': '+', 'value': 196641, 'cat': 7, 'tech': 0, 'activable': False},
196642: {'nrj': 1, 'cout': 0, 'temp': 0, 'nom': 'canonh2', 'color': [125, 13, 114], 'text': '■', 'value': 196642, 'cat': 7, 'tech': 0, 'activable': False},
196643: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern0-1', 'color': [255, 255, 255], 'text': '0', 'value': 196643, 'cat': 7, 'tech': 0, 'activable': False},
196644: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern0-2', 'color': [255, 255, 255], 'text': '0', 'value': 196644, 'cat': 7, 'tech': 0, 'activable': False},
196645: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern0-4', 'color': [255, 255, 255], 'text': '0', 'value': 196645, 'cat': 7, 'tech': 0, 'activable': False},
196646: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern1-2', 'color': [255, 255, 255], 'text': '1', 'value': 196646, 'cat': 7, 'tech': 0, 'activable': False},
196647: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern1-4', 'color': [255, 255, 255], 'text': '1', 'value': 196647, 'cat': 7, 'tech': 0, 'activable': False},
196648: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern2-4', 'color': [255, 255, 255], 'text': '2', 'value': 196648, 'cat': 7, 'tech': 0, 'activable': False},
196649: {'nrj': 0, 'cout': 250, 'temp': 0.05, 'nom': 'triern3-4', 'color': [125, 13, 114], 'text': '3', 'value': 196649, 'cat': 7, 'tech': 0, 'activable': False},
196650: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern7-8a', 'color': [125, 13, 114], 'text': '7', 'value': 196650, 'cat': 7, 'tech': 0, 'activable': True},
196651: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern6-8a', 'color': [125, 13, 114], 'text': '6', 'value': 196651, 'cat': 7, 'tech': 0, 'activable': True},
196652: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern5-8a', 'color': [125, 13, 114], 'text': '5', 'value': 196652, 'cat': 7, 'tech': 0, 'activable': True},
196653: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern4-8a', 'color': [125, 13, 114], 'text': '5', 'value': 196653, 'cat': 7, 'tech': 0, 'activable': True},
196654: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern3-8a', 'color': [125, 13, 114], 'text': '3', 'value': 196654, 'cat': 7, 'tech': 0, 'activable': True},
196655: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern2-8a', 'color': [125, 13, 114], 'text': '2', 'value': 196655, 'cat': 7, 'tech': 0, 'activable': True},
196656: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern1-8a', 'color': [125, 13, 114], 'text': '1', 'value': 196656, 'cat': 7, 'tech': 0, 'activable': True},
196657: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern0-8a', 'color': [255, 255, 255], 'text': '0', 'value': 196657, 'cat': 7, 'tech': 0, 'activable': True},
196658: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern3-4a', 'color': [125, 13, 114], 'text': '3', 'value': 196658, 'cat': 7, 'tech': 0, 'activable': True},
196659: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern2-4a', 'color': [125, 13, 114], 'text': '2', 'value': 196659, 'cat': 7, 'tech': 0, 'activable': True},
196660: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern1-4a', 'color': [125, 13, 114], 'text': '1', 'value': 196660, 'cat': 7, 'tech': 0, 'activable': True},
196661: {'nrj': 0, 'cout': 300, 'temp': 0.05, 'nom': 'triern0-4a', 'color': [255, 255, 255], 'text': '0', 'value': 196661, 'cat': 7, 'tech': 0, 'activable': True},
196662: {'nrj': 0, 'cout': 25, 'temp': 0.05, 'nom': 'dir3', 'color': [125, 13, 114], 'text': '▲', 'value': 196662, 'cat': 2, 'tech': 5, 'activable': False},
196663: {'nrj': 0, 'cout': 25, 'temp': 0.05, 'nom': 'dir4', 'color': [125, 13, 114], 'text': '▼', 'value': 196663, 'cat': 2, 'tech': 5, 'activable': False},
0: {'color': [0, 0, 0], 'nom': 'nothing', 'cout': 0, 'value': 0},
1: {'color': [240, 100, 38], 'nom': 'copper', 'cout': 1, 'value': 1},
2: {'color': [208, 213, 79], 'nom': 'fiber', 'cout': 5, 'value': 2},
4: {'color': [122, 49, 25], 'nom': 'prot', 'cout': 0, 'value': 4},
5: {'color': [75, 119, 157], 'nom': 'neut', 'cout': 0, 'value': 5},
16: {'color': [80, 80, 80], 'nom': 'tail', 'cout': 1, 'value': 16},
17: {'color': [150, 50, 50], 'nom': 'tailr', 'cout': 1, 'value': 17},
18: {'color': [50, 50, 150], 'nom': 'tailb', 'cout': 1, 'value': 18},
19: {'color': [68, 165, 68], 'nom': 'tailp', 'cout': 5, 'value': 19},
32: {'color': [80, 80, 80], 'nom': 'tail2', 'cout': 1, 'value': 32},
33: {'color': [150, 50, 50], 'nom': 'tailr2', 'cout': 1, 'value': 33},
34: {'color': [50, 50, 150], 'nom': 'tailb2', 'cout': 1, 'value': 34},
4096: {'color': [60, 60, 60], 'nom': 'head', 'cout': 1, 'value': 4096},
4352: {'color': [200, 50, 50], 'nom': 'headr', 'cout': 1, 'value': 4352},
4608: {'color': [50, 50, 200], 'nom': 'headb', 'cout': 1, 'value': 4608},
4864: {'color': [44, 120, 44], 'nom': 'headp', 'cout': 5, 'value': 4864},
8192: {'color': [40, 40, 40], 'nom': 'head2', 'cout': 1, 'value': 8192},
8448: {'color': [255, 0, 0], 'nom': 'headr2', 'cout': 1, 'value': 8448},
8704: {'color': [0, 0, 255], 'nom': 'headb2', 'cout': 1, 'value': 8704}}

menus=[
[
{'motion':'motion_motion_popup','place':'bottom','visible':True,'size':50,'variable':False,'selectable':True,'mouse':[7,5,6]},
{'motion':'motion_popup','click': ['click_run','click_stop'], 'tech':-1, 'value':['Simuler','Fin simulation'], 'size':45, 'icon': ['picture/run.png','picture/stop.png'], 'choose': 0,'variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_speed', 'tech':0, 'value':'Vitesse', 'size':45,'icon': 'picture/speed.png','variable':False,'visible':True,'separe':True,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_load', 'tech':1, 'value':'Charger', 'size':45,'icon': 'picture/raz.png','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_save', 'tech':1, 'value':'Enregistrer', 'size':45,'icon': 'picture/save.png','variable':False,'visible':True,'separe':True,'squarred':False,'active': True},
{'motion':'motion_popup','drag': 'drag_move', 'tech':-1, 'value':'Deplacer', 'size':45,'icon': 'picture/move.png','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_zoomp','tech':-1, 'value':'Zommer', 'size':45,'icon': 'picture/zoomp.png','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_zoomm', 'tech':-1, 'value':'Dezommer', 'size':45,'icon': 'picture/zoomm.png','variable':False,'visible':True,'separe':True,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_stat', 'tech':2, 'value':'Statistiques...', 'size':45,'icon': 'picture/stat.png','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_menu', 'tech':-1, 'value':'Laboratoires', 'size':45,'icon': 'picture/levels.png','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': ['click_fullscreen','click_windowed'], 'tech':-1, 'value':['Plein ecran','Fenetre'], 'size':45,'icon': ['picture/screen.png','picture/windows.png'], 'choose': 0,'variable':False,'visible':'win.width>1450','separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': ['click_sound','click_nosound'], 'tech':-1, 'value':['Activer son','Desactiver son'], 'size':45, 'icon': ['picture/sound.png','picture/nosound.png'], 'choose': 0,'variable':False,'visible':'win.width>1450','separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': ['click_tutoriel','click_popup','click_simple'], 'tech':3, 'value':['Activer Tutoriel','Activer Aide','Sans Aide/Tutoriel',], 'size':45,'icon': ['picture/tuto.png','picture/popup.png','picture/nothing.png'], 'choose': 1,'variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_settings', 'tech':-1, 'value':'Options...', 'size':45,'icon': 'picture/settings.png','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_exit', 'tech':-1, 'value':'Quitter', 'size':45,'icon': 'picture/exits.png','variable':False,'visible':True,'separe':True,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_drag_copper', 'drag': 'click_drag_copper' ,'tech':0, 'value':'Cuivre', 'size':45,'icon': [240, 100, 38],'variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_drag_fiber', 'drag': 'click_drag_fiber', 'tech':2, 'value':'Fibre', 'size':45,'icon': [208, 213, 79],'variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_drag_nothing', 'drag': 'click_drag_nothing','tech':0, 'value':'Effacer', 'size':45,'icon': [0, 0, 0],'variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_drag_transmuter', 'drag': 'click_drag_transmuter', 'tech':1, 'value':'Transmuteurs', 'size':45,'icon': '','variable':False,'visible':True,'separe':True,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_stat', 'tech':2, 'value':'Statistiques totaux', 'size':0, 'icon': 'drawstat', 'params': '''[stat[0],stat[1],stat[3],stat[4],stat[5],stat[6],stat[2],stat[7],stat[8]],[art['headb2']['color'],art['headb']['color'],art['head']['color'],art['head2']['color'],art['headr']['color'],art['headr2']['color'],art['headp']['color'],art['neut']['color'],art['prot']['color']]''', 'variable':True,'visible':'win.width<1280','separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_stat', 'tech':2, 'value':'Statistiques electrons', 'size':0, 'icon': 'drawstat', 'params': '''[stat[0],stat[1],stat[3],stat[4],stat[5],stat[6]],[art['headb2']['color'],art['headb']['color'],art['head']['color'],art['head2']['color'],art['headr']['color'],art['headr2']['color']]''', 'variable':True,'visible':'win.width>=1280','separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_stat', 'tech':2, 'value':'Statistiques hors electrons', 'size':0, 'icon': 'drawstat', 'params': '''[stat[2],stat[7],stat[8]],[art['headp']['color'],art['neut']['color'],art['prot']['color']]''','variable':True,'visible':'win.width>=1280','separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_cout', 'tech':0,'text':'#str(cout-thecout)', 'value':'Argent', 'size':140, 'icon': 'picture/cout.png','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','scroll': 'scroll_tech', 'click': 'click_tech', 'tech':1,'text':'#str(tech)', 'value':'Degre technologique', 'size':65, 'icon': 'picture/tech.png','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
]
,
[
{'motion':'motion_popup','place':'top','visible':True,'variable':False,'size':50,'selectable':False},
{'motion':'motion_popup','click': 'click_cycle','text':'#str(cycle)','text2':"#if maxcycle<99999: return str(maxcycle) else: return 'illimite'", 'tech':0, 'value':'Nb de cycles', 'size':0, 'icon': 'picture/cycle.png', 'variable':True,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_nrj','text':'#str(nrj)','text2':"#if maxnrj<99999: return str(maxnrj) else: return 'illimite'", 'tech':5, 'value':'Quantite energie', 'size':0, 'icon': 'picture/nrj.png','variable':True,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_rayon','text':'#str(rayon)','text2':"#if maxrayon<99999: return str(maxrayon) else: return 'illimite'", 'tech':6, 'value':'Niveau de rayonnements', 'size':0,'icon': 'picture/rayon.png','variable':True,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_temp','text':'#str(temp)','text2':"#if maxtemp<99999: return str(maxtemp) else: return 'illimite'", 'tech':7, 'value':'Temperature ambiante', 'size':0,'icon': 'picture/temp.png','variable':True,'visible':True,'separe':True,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_objectif', 'tech':-1, 'value':'Objectif a atteindre', 'size':44, 'icon': 'drawelement','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
{'motion':'motion_popup','click': 'click_condition', 'tech':0, 'value':'Conditions de victoire', 'size':300, 'icon': 'drawcondvictory','params': '[90,90,90]','variable':False,'visible':True,'separe':False,'squarred':False,'active': True},
],
[
{'place':'bottom+','visible':False,'size':0,'variable':True,'selectable':False},
],
[
{'place':'bottom+','visible':False,'size':0,'variable':True,'selectable':False},
]
]

write("dbdata",["worlds","art","menus"])
